// Code generated by command: go run main.go -out add.s -stubs stub.go. DO NOT EDIT.

#include "textflag.h"

// func SlideCopy(dst []byte, src []byte, lf byte, rf byte, size uint64) uint64
// Requires: BMI2
TEXT ·SlideCopy(SB), NOSPLIT, $0-72
	MOVQ dst_base+0(FP), AX
	MOVQ src_base+24(FP), CX
	MOVB lf+48(FP), DL
	MOVB rf+49(FP), BL
	MOVQ size+56(FP), SI
	XORQ DI, DI
	XORL R8, R8
	XORL R9, R9
	MOVB DL, R8
	MOVB BL, R9

loop:
	// Check If Ends
	MOVQ SI, BX
	SARQ $0x03, BX
	CMPQ BX, $0x00
	JE   done

	// Copy Left Byte
	MOVB  (CX), DL
	PEXTL R8, DX, DX
	MOVB  DL, (AX)
	INCQ  CX

	// Copy Right Byte
	MOVB  (CX), DL
	PDEPL R9, DX, DX
	ADDB  DL, (AX)
	INCQ  AX
	SUBQ  $0x08, SI
	INCQ  DI
	JMP   loop

done:
	// Store copied byte length
	MOVQ DI, ret+64(FP)
	RET
