// Code generated by command: go run main.go -out add.s -stubs stub.go. DO NOT EDIT.

package gobits

// Copy slided Buffer
func SlideCopy(dst []byte, src []byte, lf byte, rf byte, size uint64) uint64
